### PR TITLE
Bump perfetto to v31, specify C++17 requirement

### LINKED ISSUE #7: Add cross-platform GitHub Actions tests
Followup to #4 

- [x] Create a GitHub action for QC
- [x] Add test case(s) to verify that the correct dump files are indeed created

cc @benthevining

### PR DESCRIPTION
**Pull request by sudara**

### CODE REVIEW

**Comment by sudara** [comment]
@benthevining This builds fine for me locally on Windows, tried a few more things, but no luck...

**Comment by benthevining** [comment]
It also builds fine and all tests pass on my Windows machine 😬 

My best guess is that it could be an issue with the msbuild version that's installed on the GH runner, right now we're just using whatever its default is. Microsoft provides [an action](https://github.com/microsoft/setup-msbuild) for this that we could try.

**Comment by benthevining** [comment]
Scratch that, I neglected to clear out my builds folder before trying it. It does indeed fail on my Windows machine with the same error. I'll look into it.

**Comment by sudara** [comment]
Oooh, amazing, I don't think I was able to reproduce...

**Comment by benthevining** [comment]
Interestingly, the build succeeds with Clang on Windows, the error only occurs with MSVC.

**Comment by benthevining** [comment]
I'm not sure if this is a CMake or MSVC issue... I'll ask around and see if anyone else has encountered this.

**Comment by benthevining** [comment]
This is fixed by my latest commit. 

Apparently, for legacy reasons, MSVC always sets the value of `__cplusplus` to indicate C++98 unless the special flag `Zc:__cplusplus` is set... which, of course, CMake does not set by default.

See [this article](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) for more info.

**Comment by benthevining** [comment]
@sudara I believe this is ready to merge!

**Comment by sudara** [comment]
@benthevining Thanks for looking into that! 

> Apparently, for legacy reasons, MSVC always sets the value of __cplusplus to indicate C++98 unless the special flag Zc:__cplusplus is set... which, of course, CMake does not set by default.

Yikes. I wonder if this is impacting my other projects. Sorta scary that CMake doesn't do the right thing with `CMAKE_CXX_STANDARD`...

Merged!

**Comment by benthevining** [comment]
Yes, it is slightly disturbing. Kitware is aware of the issue, there's a bug filed for this.

**Pull request merged**
